AppEventsHandler = function(methods) {
  template = EventHandlerTable[['{00024413-0000-0000-C000-000000000046}']]
  createEventServerFromTemplate(methods, template, 'AppEvents'

} 
ChartEventsHandler = function(methods) {
  template = EventHandlerTable[['{0002440F-0000-0000-C000-000000000046}']]
  createEventServerFromTemplate(methods, template, 'ChartEvents'

} 
DocEventsHandler = function(methods) {
  template = EventHandlerTable[['{00024411-0000-0000-C000-000000000046}']]
  createEventServerFromTemplate(methods, template, 'DocEvents'

} 
WorkbookEventsHandler = function(methods) {
  template = EventHandlerTable[['{00024412-0000-0000-C000-000000000046}']]
  createEventServerFromTemplate(methods, template, 'WorkbookEvents'

} 
OLEObjectEventsHandler = function(methods) {
  template = EventHandlerTable[['{00024410-0000-0000-C000-000000000046}']]
  createEventServerFromTemplate(methods, template, 'OLEObjectEvents'

} 
RefreshEventsHandler = function(methods) {
  template = EventHandlerTable[['{0002441B-0000-0000-C000-000000000046}']]
  createEventServerFromTemplate(methods, template, 'RefreshEvents'

} 
