overview.html:
overview.pdf:

ifndef DYN_DOCS
DYN_DOCS=$(HOME)/Classes/StatComputing/XDynDocs/inst
endif

ifndef OMEGA_HOME
OMEGA_HOME=../../..
endif

#include $(OMEGA_HOME)/Config/GNUmakefile.config
#include $(OMEGA_HOME)/Config/GNUmakefile.xml

include $(DYN_DOCS)/Make/Makefile



# include $(OMEGA_HOME)/Config/GNUmakefile.rules